### ISSUE TITLE
0.8.0 roadmap: Addressing ROpenSci Review

### ISSUE THREAD

**Issue by sigmafelix** [NIEHS/chopin#87]
## Main functions
- [ ] Rename `par_group_grid`
- [ ] `extract_at` as the only function for extract raster values at generic polygons
- [ ] Recheck examples of wrapper functions
- [ ] Toy examples or make the current examples smaller
- [ ] `par_cut_coords`: add `sf::st_zm(drop = TRUE)`
- [ ] `extract_at_poly`: `st_crs(polys) == st_crs(surf)`
- [ ] Elegant way of argument injection in `par_grid`, `par_hierarchy`, and `par_multiraters`, i.e., avoiding positional arguments

## Auxiliary/internal functions
- [ ] Do not export aux functions
- [ ] `dep_switch`: add potential use cases, narrow the scope

## Documentation
- [ ] Clear distinction between `summarize_aw` (vector-vector) and `extract_at_buffer_kernel` (vector-raster)
- [ ] Move 2D geometries caveats to the later part of README
- [ ] Multiple point of entry: add quick start code snippets in README, introductory vignettes, and package documentation
- [ ] Remove acronym from DESCRIPTION and consider more generalized package title
- [ ] Flowchart
  - [ ] Split into clearly separate plots
  - [ ] Add explicit elaboration of the plots in README
- [ ] Reorganize vignettes
  - [ ] Benchmark cases into a separate vignette
  - [ ] Extend HPC vignettes
- [ ] Change default `future::plan` to `future::multisession`
  - [ ] Internally convert terra input to sf if `multisession` is detected ([#82](https://github.com/NIEHS/chopin/issues/82))
- [ ] Precomputing: fix broken figure paths
- [ ] Clarify inexhaustive grid in `par_group_balanced` documentation
- [ ] Add justification to all default argument values
- [ ] Fix URLs (to internal and external functions as well as internet links)
- [ ] Add `CITATION` file
- [ ] Remove `To run this example`
- [ ] Clarification of the concept of SEDC in `summarize_sedc`

## Programming practices
- [ ] Standard S3 practices for switching functions
- [ ] Add expected values in `expect_message`
- [ ] Reduce the number of `expect_no_error`
- [ ] Avoid single long tests
- [ ] Legibility of package loading codes: use `library`
- [ ] Community guidelines (i.e., `CONTRIBUTING.md`)
- [ ] Codemetar synchronization (cf. [link](https://github.com/ropensci/codemetar?tab=readme-ov-file#keep-codemetajson-up-to-date))
- [ ] Standard messaging functions instead of `cat` or `print`
- [ ] `inherits()` rather than using `grepl()` at `class()` outputs
- [ ] Add tests for different operating systems

**Comment by sigmafelix** [comment]
VSCode glitch. I'm closing this issue.
