### ISSUE TITLE
0.8.1 checklist

### ISSUE THREAD

**Issue by kyle-messier** [NIEHS/chopin#98]
- [x] resolve test-coverage-local failing
- [x] pkgdown to gh-pages rendering of chopin+chords logo is too large (https://usethis.r-lib.org/reference/use_logo.html)
- [x] version number rendering on gh-page - do not include values after #.#.# 
- [x] mermaid diagrams in README are not rendering
- [ ]  ...

**Comment by sigmafelix** [comment]
#99 and #100.
